config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :engineering_normal_salary_tables, controller: "engineering_salary_tables"
  resources :engineering_normal_with_tax_salary_tables, controller: "engineering_salary_tables"
  resources :engineering_big_table_salary_tables, controller: "engineering_salary_tables"
  resources :engineering_dong_fang_salary_tables, controller: "engineering_salary_tables"

  resources :engineering_salary_tables do
    collection do
      post 'batch_action'
      post 'import_do'
      get 'import_new'
      get 'import_demo'
      get 'export_xlsx'
    end
  end
  resources :engineering_normal_with_tax_salary_items do
    collection do
      post 'batch_action'
      post 'import_do'
      get 'import_new'
      get 'import_demo'
      get 'export_xlsx'
    end
  end
  resources :engineering_normal_salary_items do
    collection do
      post 'batch_action'
      post 'import_do'
      get 'import_new'
      get 'import_demo'
      get 'export_xlsx'
    end
  end
  resources :salary_items do
    collection do
      post 'batch_action'
      post 'import_do'
      get 'import_new'
      get 'import_demo'
      get 'export_xlsx'
    end
  end

  ActiveAdmin.routes(self)

  resources :big_contracts, only: [:create, :destroy] do
    member do
      post 'activate'
      post 'deactivate'
    end
  end

  resources :contract_files, only: [:create, :destroy] do
    collection do
      get "generate_and_download"
    end
  end
  resources :contract_templates, only: [:create, :destroy] do
    collection do
      get "generate_and_download"
    end
  end
  resources :engineering_contract_files, only: [:create, :destroy] do
    collection do
      post "generate_and_download"
    end
  end

end

app/models/sub_company.rb
class SubCompany < ActiveRecord::Base
  include PublicActivity::Model
  tracked \
    owner: ->(controller, model) { controller.try(:current_admin_user) || AdminUser.super_admin.first },
    params: {
      name: ->(controller, model) { [model.class.model_name.human, model.try(:name)].compact.join(' - ') },
    }

  # Business
  has_many :normal_corporations
  mount_uploader :busi_contract_template, ContractTemplateUploader
  has_many :normal_staffs

  # Engineer
  has_many :projects, class: EngineeringProject
  has_many :big_contracts
  mount_uploader :engi_contract_template, ContractTemplateUploader
  mount_uploader :engi_protocol_template, ContractTemplateUploader

  has_many :invoice_settings
  has_many :invoices

  # Validation
  validates_uniqueness_of :name

  # Scope
  scope :query_name, ->(name){ where("name LIKE '%#{name}%'") }
  scope :hr, ->{ where(has_engineering_relation: true) }

  class << self
    def policy_class
      SubCompanyPolicy
    end

    def ordered_columns(without_base_keys: false, without_foreign_keys: false)
      names = column_names.map(&:to_sym)

      names -= %i(id created_at updated_at) if without_base_keys
      names -= %i() if without_foreign_keys

      names
    end

    def columns_of(type)
      self.columns_hash.select{|k,v| v.type == type }.keys.map(&:to_sym)
    end

    def hr_options
      hr.select(:id,:name).map{|sc| [sc.name, sc.id]}
    end

    def as_option
      select(:id, :name).map{|sc| [sc.name, sc.id]}
    end
  end

  def customers
    ids = projects.pluck(:engineering_customer_id)
    EngineeringCustomer.where(id: ids)
  end

  def corporations
    ids = projects.pluck(:engineering_corp_id)
    EngineeringCorp.where(id: ids)
  end

  def last_invoice_setting
    is = invoice_settings.last
    if is.present?
      { category: is.category, code: is.code, encoding: is.next_encoding }
    else
      { category: 'normal', code: '', encoding: '' }
    end
  end
end

app/views/sub_companies/_contract_template.html.erb
<ul>
  <% templates.each do |template| %>
    <li>
      <span><%= template.contract_identifier %></span>
      <span>( <%= link_to '下载', template.contract.url %>
        <%= form_tag(contract_template_path(template), method: :delete, class: 'form_tag') do %>
          <%= link_to "删除",  "#", :onclick=>"$(this).closest('form').submit()" %>
        <% end %>
         )
      </span>
    </li>
  <% end %>
</ul>

<%= form_for ContractTemplate.new, url: contract_templates_path, class: 'form_tag' do |f| %>
  <%= f.file_field :contract %>
  <%= f.hidden_field :sub_company_id, value: company.id %>

  <%= link_to "上传",  "#", :onclick=>"$(this).closest('form').submit()" %>
<% end %>

app/views/sub_companies/_engi_template_display.html.erb
<% files = Array.wrap(company.send(field)) %>

<div class='template_file_upload_panel'>
  <ul>
    <% Array.wrap(files).each do |file| %>
      <% next unless company.public_send("#{field}?") %>
      <li>
        <span><%= company.public_send("#{field}_identifier") %></span>
        <span>( <%= link_to '下载', file.url %>
          <%= form_tag(remove_template_sub_company_path(company), method: :delete, class: 'form_tag') do %>
            <%= hidden_field_tag :field, field %>
            <%= link_to "删除",  "#", :onclick=>"$(this).closest('form').submit()" %>
          <% end %>
           )
        </span>
      </li>
    <% end %>
  </ul>
</div>

app/views/sub_companies/_engi_template_upload.html.erb
<% override ||= false %>

<div class='engi_template_file_upload_panel'>
  <%= form_tag add_template_sub_company_path(company), class: 'form_tag', multipart: true do |f| %>
    <%= hidden_field_tag :field, field %>
    <%= file_field_tag :file %>
    <%= link_to "上传",  "#", :onclick=>"$(this).closest('form').submit()" %>
    <% if override %>
      <%= label_tag "（注：上传操作会覆盖已有文件）" %>
    <% end %>
  <% end %>
</div>