config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :engineering_normal_salary_tables, controller: "engineering_salary_tables"
  resources :engineering_normal_with_tax_salary_tables, controller: "engineering_salary_tables"
  resources :engineering_big_table_salary_tables, controller: "engineering_salary_tables"
  resources :engineering_dong_fang_salary_tables, controller: "engineering_salary_tables"

  resources :engineering_salary_tables do
    collection do
      post 'batch_action'
      post 'import_do'
      get 'import_new'
      get 'import_demo'
      get 'export_xlsx'
    end
  end
  resources :engineering_normal_with_tax_salary_items do
    collection do
      post 'batch_action'
      post 'import_do'
      get 'import_new'
      get 'import_demo'
      get 'export_xlsx'
    end
  end
  resources :engineering_normal_salary_items do
    collection do
      post 'batch_action'
      post 'import_do'
      get 'import_new'
      get 'import_demo'
      get 'export_xlsx'
    end
  end
  resources :salary_items do
    collection do
      post 'batch_action'
      post 'import_do'
      get 'import_new'
      get 'import_demo'
      get 'export_xlsx'
    end
  end

  ActiveAdmin.routes(self)

  resources :big_contracts, only: [:create, :destroy] do
    member do
      post 'activate'
      post 'deactivate'
    end
  end

  resources :contract_files, only: [:create, :destroy] do
    collection do
      get "generate_and_download"
    end
  end
  resources :contract_templates, only: [:create, :destroy] do
    collection do
      get "generate_and_download"
    end
  end
  resources :engineering_contract_files, only: [:create, :destroy] do
    collection do
      post "generate_and_download"
    end
  end

end

app/views/shared/_contract.html.erb
<ul>
  <% sub_company.contract_templates.each_with_index do |ct, idx| %>
    <li>
      <span><%= ct.file.basename %></span>
      <span>( <%= link_to '生成合同文件', generate_and_download_contract_files_path + "?sub_company_id=#{sub_company.id}&template=#{idx}" %> )
      </span>
    </li>
  <% end %>
</ul>

<ul>
  <% sub_company.contract_files.custom.each do |cf| %>
    <li>
      <span><%= cf.contract_identifier %></span>
      <span>( <%= link_to '下载', cf.contract.url %> 
        <%= form_tag(contract_file_path(cf), method: :delete, class: 'form_tag') do %>
          <%= link_to "删除",  "#", :onclick=>"$(this).closest('form').submit()" %>
        <% end %>
         )
      </span>
    </li>
  <% end %>
</ul>

<%= form_for ContractFile.new, url: contract_files_path, class: 'form_tag' do |f| %>
  <%= f.file_field :contract %>
  <%= f.hidden_field :sub_company_id, value: sub_company.id %>
  <%= link_to "上传",  "#", :onclick=>"$(this).closest('form').submit()" %>
<% end %>

app/views/shared/_contract_engineering.html.erb
<% auto_generate ||= nil %>

<div class='contract_file_upload_panel'>
  <% if auto_generate %>
    <ul>
      <li>
        <span><%= link_to '自动生成', '#', onclick: "window.location='#{generate_and_download_engineering_contract_files_path}?engineering_project_id=#{engineering_project_id}'" %>
      </li>
    </ul>
  <% end %>
  <ul>
    <% contract_files.each do |cf| %>
      <li>
        <span><%= cf.contract_identifier %></span>
        <span>( <%= link_to '下载', cf.contract.url %> 
          <%= form_tag(engineering_contract_file_path(cf), method: :delete, class: 'form_tag') do %>
            <%= link_to "删除",  "#", :onclick=>"$(this).closest('form').submit()" %>
          <% end %>
           )
        </span>
      </li>
    <% end %>
  </ul>

  <%= form_for EngineeringContractFile.new, url: engineering_contract_files_path, class: 'form_tag' do |f| %>
    <%= f.file_field :contract %>
    <%= f.hidden_field :engineering_project_id, value: engineering_project_id %>
    <%= f.hidden_field :role, value: role %>
    <%= link_to "上传",  "#", :onclick=>"$(this).closest('form').submit()" %>
  <% end %>
</div>

app/views/shared/_contract_engineering_list.html.erb
<div class='contract_file_upload_panel'>
  <ul>
    <% contract_files.each do |cf| %>
      <li>
        <span><%= cf.contract_identifier %></span>
        <span>( <%= link_to '下载', cf.contract.url %> 
          <%= form_tag(engineering_contract_file_path(cf), method: :delete, class: 'form_tag') do %>
            <%= link_to "删除",  "#", :onclick=>"$(this).closest('form').submit()" %>
          <% end %>
           )
        </span>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_contract_engineering_upload_form.html.erb
<%= form_for EngineeringContractFile.new, url: engineering_contract_files_path, class: 'form_tag' do |f| %>
  <%= f.file_field :contract %>
  <%= f.hidden_field :engineering_project_id, value: engineering_project_id %>
  <%= f.hidden_field :role, value: role %>
  <%= link_to "上传",  "#", :onclick=>"$(this).closest('form').submit()" %>
<% end %>