config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :engineering_normal_salary_tables, controller: "engineering_salary_tables"
  resources :engineering_normal_with_tax_salary_tables, controller: "engineering_salary_tables"
  resources :engineering_big_table_salary_tables, controller: "engineering_salary_tables"
  resources :engineering_dong_fang_salary_tables, controller: "engineering_salary_tables"

  resources :engineering_salary_tables do
    collection do
      post 'batch_action'
      post 'import_do'
      get 'import_new'
      get 'import_demo'
      get 'export_xlsx'
    end
  end
  resources :engineering_normal_with_tax_salary_items do
    collection do
      post 'batch_action'
      post 'import_do'
      get 'import_new'
      get 'import_demo'
      get 'export_xlsx'
    end
  end
  resources :engineering_normal_salary_items do
    collection do
      post 'batch_action'
      post 'import_do'
      get 'import_new'
      get 'import_demo'
      get 'export_xlsx'
    end
  end
  resources :salary_items do
    collection do
      post 'batch_action'
      post 'import_do'
      get 'import_new'
      get 'import_demo'
      get 'export_xlsx'
    end
  end

  ActiveAdmin.routes(self)

  resources :big_contracts, only: [:create, :destroy] do
    member do
      post 'activate'
      post 'deactivate'
    end
  end

  resources :contract_files, only: [:create, :destroy] do
    collection do
      get "generate_and_download"
    end
  end
  resources :contract_templates, only: [:create, :destroy] do
    collection do
      get "generate_and_download"
    end
  end
  resources :engineering_contract_files, only: [:create, :destroy] do
    collection do
      post "generate_and_download"
    end
  end

end

app/models/engineering_corp.rb
class EngineeringCorp < ActiveRecord::Base
  include PublicActivity::Model
  tracked \
    owner: ->(controller, _model) { controller.try(:current_admin_user) || AdminUser.super_admin.first },
    params: {
      name: ->(_controller, model) { [model.class.model_name.human, model.try(:name)].compact.join(' - ') }
    }

  has_many :projects, class: EngineeringProject
  has_many :big_contracts, -> { order(enable: :desc) }, dependent: :destroy

  class << self
    def policy_class
      EngineeringCorpPolicy
    end

    def ordered_columns(without_base_keys: false, without_foreign_keys: false)
      names = column_names.map(&:to_sym) + %i[contract_start_date contract_end_date]

      names -= %i[id created_at updated_at] if without_base_keys
      names -= %i[] if without_foreign_keys

      names
    end

    def export_xlsx(options: {})
      filename = "#{I18n.t("activerecord.models.#{name.underscore}")}_#{Time.stamp}.xlsx"
      filepath = EXPORT_PATH.join filename

      collection = all
      collection = if options[:selected].present?
                     collection.where(id: options[:selected])
                   else
                     collection.ransack(options).result
                   end

      columns = columns_based_on(options: options)

      Axlsx::Package.new do |p|
        p.workbook.add_worksheet(name: name) do |sheet|
          sheet.add_row columns.map { |col| human_attribute_name(col) }

          collection.each do |item|
            stats = \
              columns.map do |col|
                item.send(col)
              end
            sheet.add_row stats
          end
        end
        p.serialize(filepath.to_s)
      end

      filepath
    end

    def columns_based_on(options: {})
      if options[:columns].present?
        options[:columns].map(&:to_sym)
      else
        ordered_columns(without_base_keys: true, without_foreign_keys: true)
      end
    end

    def as_option
      self.select(:id, :name, :created_at).order('created_at DESC').map do |ec|
        display_name = "#{ec.name} - #{ec.created_at.to_date}"
        [display_name, ec.id]
      end
    end
  end

  def customers
    ids = projects.pluck(:engineering_customer_id)
    EngineeringCustomer.where(id: ids)
  end

  def sub_companies
    ids = projects.pluck(:sub_company_id)
    SubCompany.where(id: ids)
  end

  def contract_start_date
    big_contracts.enable.map(&:start_date).min
  end

  def contract_end_date
    big_contracts.enable.map(&:end_date).max
  end

  def due?
    return false if contract_end_date.nil?

    Date.today + 1.month >= contract_end_date
  end

  ransacker :sub_company, formatter: lambda { |qid|
    sub_company = SubCompany.find(qid)
    sub_company.projects.pluck(:engineering_corp_id).compact.uniq
  } do |parent|
    parent.table[:id]
  end
end

app/views/engineering_corps/_contract_list.html.erb
<div class='contract_file_upload_panel'>
  <ul>
    <% contract_files.each do |cf| %>
      <li>
        <span><%= cf.to_s %></span>
        <span>( <%= link_to '下载', cf.contract.url %> 
          <%= form_tag(big_contract_path(cf), method: :delete, class: 'form_tag') do %>
            <%= link_to "删除",  "#", :onclick=>"$(this).closest('form').submit()" %>
          <% end %>
          <% if cf.enable %>
            <%= form_tag(deactivate_big_contract_path(cf), method: :post, class: 'form_tag') do %>
              <%= link_to "注销",  "#", :onclick=>"$(this).closest('form').submit()" %>
            <% end %>
            <span class='active_big_contract'>正在使用</span>
          <% else %>
            <%= form_tag(activate_big_contract_path(cf), method: :post, class: 'form_tag') do %>
              <%= link_to "激活",  "#", :onclick=>"$(this).closest('form').submit()" %>
            <% end %>
          <% end %>
           )
        </span>
      </li>
    <% end %>
  </ul>
</div>

app/views/engineering_corps/_contract_upload.html.erb
<% object ||= nil %>

<%= form_tag big_contracts_path, class: 'form_tag', multipart: true do |f| %>
  <%= hidden_field_tag :engineering_corp_id, object.id %>

  <%= field_set_tag nil, class: 'inputs' do %>
    <ol>
      <li>
        <%= label_tag '吉易子公司' %>
        <%= select_tag :sub_company_id, options_for_select(SubCompany.hr.pluck(:name, :id)) %>
      </li>
      <li>
        <%= label_tag '开始时间' %>
        <%= date_field_tag :start_date, Date.today %>
      </li>
      <li>
        <%= label_tag '结束时间' %>
        <%= date_field_tag :end_date, Date.today %>
      </li>
      <li>
        <%= label_tag '上传文件' %>
        <%= file_field_tag :contract %>
      </li>
    </ol>
  <% end %>
  <%= button_tag "生成" %>
<% end %>